export const userLoginPath = '/api/user/login'
export const userRegisterPath = '/api/user/register'
export const userVerifyPath = '/api/user/verify'
export const unitsPath = '/api/units'
export const userProgressPath = '/api/user/progress'
export const userCheckinStatsPath = '/api/user/checkin-stats'
export const userCheckinPath = '/api/user/checkin'
export const userLogoutPath = '/api/user/logout'